pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author=tkawachi
      - check-success~=build
      - check-success~=security/snyk
    actions:
      merge:
        method: merge
