pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - check-success=Scala CI / build (pull_request)
      - check-success=security/snyk (tkawachi)
    actions:
      merge:
        method: merge
